import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="flex items-center justify-between px-6 py-4 bg-white shadow-md mb-6">
  {/* Logo / Home */}
  <Link
    href="/"
    className="text-xl font-bold text-gray-800 hover:text-orange-500 transition"
  >
    Home
  </Link>

  {/* Menu */}
  <div className="flex items-center gap-6">
    <Link
      href="/login"
      className="text-gray-600 hover:text-orange-500 font-medium transition"
    >
      Login
    </Link>

    <Link
      href="/admin"
      className="bg-orange-500 hover:bg-orange-600 text-white px-4 py-2 rounded-lg transition"
    >
      Admin
    </Link>
  </div>
</nav>
        {children}
      </body>
    </html>
  );
}
